// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF8PcTPppAgdiTf853TSjDOruqoq4fp7g',
    appId: '1:51934333273:web:0822d680913acc2e766448',
    messagingSenderId: '51934333273',
    projectId: 'barberia-7e151',
    authDomain: 'barberia-7e151.firebaseapp.com',
    storageBucket: 'barberia-7e151.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1Qd-5Dl6mwgM_oPDrpLeKwDHFaFM4o8',
    appId: '1:51934333273:android:026fcf39ebafeffe766448',
    messagingSenderId: '51934333273',
    projectId: 'barberia-7e151',
    storageBucket: 'barberia-7e151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDob5FD0zTY_iYHIGj9MxW1LkTQoCK6YGw',
    appId: '1:51934333273:ios:d28d2edf0d76a346766448',
    messagingSenderId: '51934333273',
    projectId: 'barberia-7e151',
    storageBucket: 'barberia-7e151.firebasestorage.app',
    iosBundleId: 'com.dara.barberia',
  );

}